// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pos/v1/sale.proto

package pos

import (
	common "github.com/rp-game/fnbpos-pb/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Nhánh compensation của saga bán→trừ-kho — rẽ theo reason.
type ReversalReason int32

const (
	ReversalReason_REVERSAL_REASON_UNSPECIFIED ReversalReason = 0
	ReversalReason_VOID                        ReversalReason = 1 // huỷ dòng chưa chế biến → hoàn kho
	ReversalReason_REFUND                      ReversalReason = 2 // hoàn tiền
	ReversalReason_QTY_ADJUST                  ReversalReason = 3 // sửa số lượng (reversal một phần — new_qty thêm ở G0)
)

// Enum value maps for ReversalReason.
var (
	ReversalReason_name = map[int32]string{
		0: "REVERSAL_REASON_UNSPECIFIED",
		1: "VOID",
		2: "REFUND",
		3: "QTY_ADJUST",
	}
	ReversalReason_value = map[string]int32{
		"REVERSAL_REASON_UNSPECIFIED": 0,
		"VOID":                        1,
		"REFUND":                      2,
		"QTY_ADJUST":                  3,
	}
)

func (x ReversalReason) Enum() *ReversalReason {
	p := new(ReversalReason)
	*p = x
	return p
}

func (x ReversalReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReversalReason) Descriptor() protoreflect.EnumDescriptor {
	return file_pos_v1_sale_proto_enumTypes[0].Descriptor()
}

func (ReversalReason) Type() protoreflect.EnumType {
	return &file_pos_v1_sale_proto_enumTypes[0]
}

func (x ReversalReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReversalReason.Descriptor instead.
func (ReversalReason) EnumDescriptor() ([]byte, []int) {
	return file_pos_v1_sale_proto_rawDescGZIP(), []int{0}
}

// pos.sale.committed — pos -> fnb (async, publish).
// Idempotent theo (tenant_id, order_id, sale_line_id, line_revision).
type SaleCommitted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *common.Envelope       `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	OutletId      string                 `protobuf:"bytes,2,opt,name=outlet_id,json=outletId,proto3" json:"outlet_id,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,3,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"` // fnb trừ kho từ kho này
	OrderId       string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Lines         []*SaleLine            `protobuf:"bytes,6,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleCommitted) Reset() {
	*x = SaleCommitted{}
	mi := &file_pos_v1_sale_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleCommitted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleCommitted) ProtoMessage() {}

func (x *SaleCommitted) ProtoReflect() protoreflect.Message {
	mi := &file_pos_v1_sale_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleCommitted.ProtoReflect.Descriptor instead.
func (*SaleCommitted) Descriptor() ([]byte, []int) {
	return file_pos_v1_sale_proto_rawDescGZIP(), []int{0}
}

func (x *SaleCommitted) GetEnvelope() *common.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *SaleCommitted) GetOutletId() string {
	if x != nil {
		return x.OutletId
	}
	return ""
}

func (x *SaleCommitted) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *SaleCommitted) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SaleCommitted) GetLines() []*SaleLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type SaleLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaleLineId    string                 `protobuf:"bytes,1,opt,name=sale_line_id,json=saleLineId,proto3" json:"sale_line_id,omitempty"`
	LineRevision  uint32                 `protobuf:"varint,2,opt,name=line_revision,json=lineRevision,proto3" json:"line_revision,omitempty"`
	MenuItemId    string                 `protobuf:"bytes,3,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	VariationId   string                 `protobuf:"bytes,4,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`
	Qty           *common.Quantity       `protobuf:"bytes,5,opt,name=qty,proto3" json:"qty,omitempty"`                                       // qty/weight + UoM (cân ký, định lượng)
	Modifiers     []*Modifier            `protobuf:"bytes,6,rep,name=modifiers,proto3" json:"modifiers,omitempty"`                           // modifier mang định lượng NVL
	ComboChoices  []string               `protobuf:"bytes,7,rep,name=combo_choices,json=comboChoices,proto3" json:"combo_choices,omitempty"` // nhánh combo swappable đã chọn (component_ref)
	UnitPrice     *common.Money          `protobuf:"bytes,8,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`          // giá đã chốt (COGS join theo sale_line_id)
	LineDiscount  *common.Money          `protobuf:"bytes,9,opt,name=line_discount,json=lineDiscount,proto3" json:"line_discount,omitempty"` // chiết khấu dòng (DEC-05)
	Tax           *common.Money          `protobuf:"bytes,10,opt,name=tax,proto3" json:"tax,omitempty"`                                      // thuế dòng theo tax_group (DEC-05)
	CogsHint      *common.Money          `protobuf:"bytes,11,opt,name=cogs_hint,json=cogsHint,proto3" json:"cogs_hint,omitempty"`            // COGS gợi ý (báo cáo biên lợi nhuận M13)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleLine) Reset() {
	*x = SaleLine{}
	mi := &file_pos_v1_sale_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleLine) ProtoMessage() {}

func (x *SaleLine) ProtoReflect() protoreflect.Message {
	mi := &file_pos_v1_sale_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleLine.ProtoReflect.Descriptor instead.
func (*SaleLine) Descriptor() ([]byte, []int) {
	return file_pos_v1_sale_proto_rawDescGZIP(), []int{1}
}

func (x *SaleLine) GetSaleLineId() string {
	if x != nil {
		return x.SaleLineId
	}
	return ""
}

func (x *SaleLine) GetLineRevision() uint32 {
	if x != nil {
		return x.LineRevision
	}
	return 0
}

func (x *SaleLine) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *SaleLine) GetVariationId() string {
	if x != nil {
		return x.VariationId
	}
	return ""
}

func (x *SaleLine) GetQty() *common.Quantity {
	if x != nil {
		return x.Qty
	}
	return nil
}

func (x *SaleLine) GetModifiers() []*Modifier {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

func (x *SaleLine) GetComboChoices() []string {
	if x != nil {
		return x.ComboChoices
	}
	return nil
}

func (x *SaleLine) GetUnitPrice() *common.Money {
	if x != nil {
		return x.UnitPrice
	}
	return nil
}

func (x *SaleLine) GetLineDiscount() *common.Money {
	if x != nil {
		return x.LineDiscount
	}
	return nil
}

func (x *SaleLine) GetTax() *common.Money {
	if x != nil {
		return x.Tax
	}
	return nil
}

func (x *SaleLine) GetCogsHint() *common.Money {
	if x != nil {
		return x.CogsHint
	}
	return nil
}

type Modifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModifierId    string                 `protobuf:"bytes,1,opt,name=modifier_id,json=modifierId,proto3" json:"modifier_id,omitempty"`
	Qty           *common.Quantity       `protobuf:"bytes,2,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Modifier) Reset() {
	*x = Modifier{}
	mi := &file_pos_v1_sale_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Modifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Modifier) ProtoMessage() {}

func (x *Modifier) ProtoReflect() protoreflect.Message {
	mi := &file_pos_v1_sale_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Modifier.ProtoReflect.Descriptor instead.
func (*Modifier) Descriptor() ([]byte, []int) {
	return file_pos_v1_sale_proto_rawDescGZIP(), []int{2}
}

func (x *Modifier) GetModifierId() string {
	if x != nil {
		return x.ModifierId
	}
	return ""
}

func (x *Modifier) GetQty() *common.Quantity {
	if x != nil {
		return x.Qty
	}
	return nil
}

// pos.kitchen.<tenant>.<outlet>.ticket — pos -> KDS (qua stream POS_KITCHEN + WS gateway). v0.4.0.
type KitchenTicket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *common.Envelope       `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PublicId      string                 `protobuf:"bytes,3,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	OutletId      string                 `protobuf:"bytes,4,opt,name=outlet_id,json=outletId,proto3" json:"outlet_id,omitempty"`
	TerminalId    string                 `protobuf:"bytes,5,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	StaffId       string                 `protobuf:"bytes,6,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Lines         []*KitchenLine         `protobuf:"bytes,7,rep,name=lines,proto3" json:"lines,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,8,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KitchenTicket) Reset() {
	*x = KitchenTicket{}
	mi := &file_pos_v1_sale_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KitchenTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KitchenTicket) ProtoMessage() {}

func (x *KitchenTicket) ProtoReflect() protoreflect.Message {
	mi := &file_pos_v1_sale_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KitchenTicket.ProtoReflect.Descriptor instead.
func (*KitchenTicket) Descriptor() ([]byte, []int) {
	return file_pos_v1_sale_proto_rawDescGZIP(), []int{3}
}

func (x *KitchenTicket) GetEnvelope() *common.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *KitchenTicket) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *KitchenTicket) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *KitchenTicket) GetOutletId() string {
	if x != nil {
		return x.OutletId
	}
	return ""
}

func (x *KitchenTicket) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *KitchenTicket) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *KitchenTicket) GetLines() []*KitchenLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *KitchenTicket) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

type KitchenLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItemId    string                 `protobuf:"bytes,1,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // tên món (kèm biến thể)
	Qty           *common.Quantity       `protobuf:"bytes,3,opt,name=qty,proto3" json:"qty,omitempty"`
	Modifiers     []string               `protobuf:"bytes,4,rep,name=modifiers,proto3" json:"modifiers,omitempty"` // code/tên modifier (hiển thị bếp)
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KitchenLine) Reset() {
	*x = KitchenLine{}
	mi := &file_pos_v1_sale_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KitchenLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KitchenLine) ProtoMessage() {}

func (x *KitchenLine) ProtoReflect() protoreflect.Message {
	mi := &file_pos_v1_sale_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KitchenLine.ProtoReflect.Descriptor instead.
func (*KitchenLine) Descriptor() ([]byte, []int) {
	return file_pos_v1_sale_proto_rawDescGZIP(), []int{4}
}

func (x *KitchenLine) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *KitchenLine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KitchenLine) GetQty() *common.Quantity {
	if x != nil {
		return x.Qty
	}
	return nil
}

func (x *KitchenLine) GetModifiers() []string {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

func (x *KitchenLine) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// pos.kitchen.<tenant>.<outlet>.update — cập nhật vòng đời vé bếp (bump/recall/ready/void). v0.5.0.
type KitchenTicketUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *common.Envelope       `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OutletId      string                 `protobuf:"bytes,3,opt,name=outlet_id,json=outletId,proto3" json:"outlet_id,omitempty"`
	LineNo        int32                  `protobuf:"varint,4,opt,name=line_no,json=lineNo,proto3" json:"line_no,omitempty"` // 0 = cả vé
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                // new|preparing|ready|bumped|recalled|voided
	Station       string                 `protobuf:"bytes,6,opt,name=station,proto3" json:"station,omitempty"`
	AtUnix        int64                  `protobuf:"varint,7,opt,name=at_unix,json=atUnix,proto3" json:"at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KitchenTicketUpdate) Reset() {
	*x = KitchenTicketUpdate{}
	mi := &file_pos_v1_sale_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KitchenTicketUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KitchenTicketUpdate) ProtoMessage() {}

func (x *KitchenTicketUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pos_v1_sale_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KitchenTicketUpdate.ProtoReflect.Descriptor instead.
func (*KitchenTicketUpdate) Descriptor() ([]byte, []int) {
	return file_pos_v1_sale_proto_rawDescGZIP(), []int{5}
}

func (x *KitchenTicketUpdate) GetEnvelope() *common.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *KitchenTicketUpdate) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *KitchenTicketUpdate) GetOutletId() string {
	if x != nil {
		return x.OutletId
	}
	return ""
}

func (x *KitchenTicketUpdate) GetLineNo() int32 {
	if x != nil {
		return x.LineNo
	}
	return 0
}

func (x *KitchenTicketUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KitchenTicketUpdate) GetStation() string {
	if x != nil {
		return x.Station
	}
	return ""
}

func (x *KitchenTicketUpdate) GetAtUnix() int64 {
	if x != nil {
		return x.AtUnix
	}
	return 0
}

// pos.sale.reversed — void/refund/sửa qty. Idempotent theo reversal_id.
type SaleReversed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *common.Envelope       `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	ReversalId    string                 `protobuf:"bytes,2,opt,name=reversal_id,json=reversalId,proto3" json:"reversal_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SaleLineId    string                 `protobuf:"bytes,4,opt,name=sale_line_id,json=saleLineId,proto3" json:"sale_line_id,omitempty"`
	LineRevision  uint32                 `protobuf:"varint,5,opt,name=line_revision,json=lineRevision,proto3" json:"line_revision,omitempty"` // bản committed đang bị đảo
	Reason        ReversalReason         `protobuf:"varint,6,opt,name=reason,proto3,enum=fnbpos.pos.v1.ReversalReason" json:"reason,omitempty"`
	NewQty        *common.Quantity       `protobuf:"bytes,7,opt,name=new_qty,json=newQty,proto3" json:"new_qty,omitempty"` // reversal MỘT PHẦN (QTY_ADJUST): số lượng còn lại
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleReversed) Reset() {
	*x = SaleReversed{}
	mi := &file_pos_v1_sale_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleReversed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleReversed) ProtoMessage() {}

func (x *SaleReversed) ProtoReflect() protoreflect.Message {
	mi := &file_pos_v1_sale_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleReversed.ProtoReflect.Descriptor instead.
func (*SaleReversed) Descriptor() ([]byte, []int) {
	return file_pos_v1_sale_proto_rawDescGZIP(), []int{6}
}

func (x *SaleReversed) GetEnvelope() *common.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *SaleReversed) GetReversalId() string {
	if x != nil {
		return x.ReversalId
	}
	return ""
}

func (x *SaleReversed) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *SaleReversed) GetSaleLineId() string {
	if x != nil {
		return x.SaleLineId
	}
	return ""
}

func (x *SaleReversed) GetLineRevision() uint32 {
	if x != nil {
		return x.LineRevision
	}
	return 0
}

func (x *SaleReversed) GetReason() ReversalReason {
	if x != nil {
		return x.Reason
	}
	return ReversalReason_REVERSAL_REASON_UNSPECIFIED
}

func (x *SaleReversed) GetNewQty() *common.Quantity {
	if x != nil {
		return x.NewQty
	}
	return nil
}

var File_pos_v1_sale_proto protoreflect.FileDescriptor

const file_pos_v1_sale_proto_rawDesc = "" +
	"\n" +
	"\x11pos/v1/sale.proto\x12\rfnbpos.pos.v1\x1a\x18common/v1/envelope.proto\"\xd7\x01\n" +
	"\rSaleCommitted\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.fnbpos.common.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\toutlet_id\x18\x02 \x01(\tR\boutletId\x12!\n" +
	"\fwarehouse_id\x18\x03 \x01(\tR\vwarehouseId\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\x12-\n" +
	"\x05lines\x18\x06 \x03(\v2\x17.fnbpos.pos.v1.SaleLineR\x05linesJ\x04\b\x05\x10\x06\"\xf7\x03\n" +
	"\bSaleLine\x12 \n" +
	"\fsale_line_id\x18\x01 \x01(\tR\n" +
	"saleLineId\x12#\n" +
	"\rline_revision\x18\x02 \x01(\rR\flineRevision\x12 \n" +
	"\fmenu_item_id\x18\x03 \x01(\tR\n" +
	"menuItemId\x12!\n" +
	"\fvariation_id\x18\x04 \x01(\tR\vvariationId\x12,\n" +
	"\x03qty\x18\x05 \x01(\v2\x1a.fnbpos.common.v1.QuantityR\x03qty\x125\n" +
	"\tmodifiers\x18\x06 \x03(\v2\x17.fnbpos.pos.v1.ModifierR\tmodifiers\x12#\n" +
	"\rcombo_choices\x18\a \x03(\tR\fcomboChoices\x126\n" +
	"\n" +
	"unit_price\x18\b \x01(\v2\x17.fnbpos.common.v1.MoneyR\tunitPrice\x12<\n" +
	"\rline_discount\x18\t \x01(\v2\x17.fnbpos.common.v1.MoneyR\flineDiscount\x12)\n" +
	"\x03tax\x18\n" +
	" \x01(\v2\x17.fnbpos.common.v1.MoneyR\x03tax\x124\n" +
	"\tcogs_hint\x18\v \x01(\v2\x17.fnbpos.common.v1.MoneyR\bcogsHint\"Y\n" +
	"\bModifier\x12\x1f\n" +
	"\vmodifier_id\x18\x01 \x01(\tR\n" +
	"modifierId\x12,\n" +
	"\x03qty\x18\x02 \x01(\v2\x1a.fnbpos.common.v1.QuantityR\x03qty\"\xb2\x02\n" +
	"\rKitchenTicket\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.fnbpos.common.v1.EnvelopeR\benvelope\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1b\n" +
	"\tpublic_id\x18\x03 \x01(\tR\bpublicId\x12\x1b\n" +
	"\toutlet_id\x18\x04 \x01(\tR\boutletId\x12\x1f\n" +
	"\vterminal_id\x18\x05 \x01(\tR\n" +
	"terminalId\x12\x19\n" +
	"\bstaff_id\x18\x06 \x01(\tR\astaffId\x120\n" +
	"\x05lines\x18\a \x03(\v2\x1a.fnbpos.pos.v1.KitchenLineR\x05lines\x12&\n" +
	"\x0fcreated_at_unix\x18\b \x01(\x03R\rcreatedAtUnix\"\xa3\x01\n" +
	"\vKitchenLine\x12 \n" +
	"\fmenu_item_id\x18\x01 \x01(\tR\n" +
	"menuItemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x03qty\x18\x03 \x01(\v2\x1a.fnbpos.common.v1.QuantityR\x03qty\x12\x1c\n" +
	"\tmodifiers\x18\x04 \x03(\tR\tmodifiers\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"\xe9\x01\n" +
	"\x13KitchenTicketUpdate\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.fnbpos.common.v1.EnvelopeR\benvelope\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1b\n" +
	"\toutlet_id\x18\x03 \x01(\tR\boutletId\x12\x17\n" +
	"\aline_no\x18\x04 \x01(\x05R\x06lineNo\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\astation\x18\x06 \x01(\tR\astation\x12\x17\n" +
	"\aat_unix\x18\a \x01(\x03R\x06atUnix\"\xb5\x02\n" +
	"\fSaleReversed\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.fnbpos.common.v1.EnvelopeR\benvelope\x12\x1f\n" +
	"\vreversal_id\x18\x02 \x01(\tR\n" +
	"reversalId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12 \n" +
	"\fsale_line_id\x18\x04 \x01(\tR\n" +
	"saleLineId\x12#\n" +
	"\rline_revision\x18\x05 \x01(\rR\flineRevision\x125\n" +
	"\x06reason\x18\x06 \x01(\x0e2\x1d.fnbpos.pos.v1.ReversalReasonR\x06reason\x123\n" +
	"\anew_qty\x18\a \x01(\v2\x1a.fnbpos.common.v1.QuantityR\x06newQty*W\n" +
	"\x0eReversalReason\x12\x1f\n" +
	"\x1bREVERSAL_REASON_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04VOID\x10\x01\x12\n" +
	"\n" +
	"\x06REFUND\x10\x02\x12\x0e\n" +
	"\n" +
	"QTY_ADJUST\x10\x03B%Z#github.com/rp-game/fnbpos-pb/v1/posb\x06proto3"

var (
	file_pos_v1_sale_proto_rawDescOnce sync.Once
	file_pos_v1_sale_proto_rawDescData []byte
)

func file_pos_v1_sale_proto_rawDescGZIP() []byte {
	file_pos_v1_sale_proto_rawDescOnce.Do(func() {
		file_pos_v1_sale_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pos_v1_sale_proto_rawDesc), len(file_pos_v1_sale_proto_rawDesc)))
	})
	return file_pos_v1_sale_proto_rawDescData
}

var file_pos_v1_sale_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pos_v1_sale_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pos_v1_sale_proto_goTypes = []any{
	(ReversalReason)(0),         // 0: fnbpos.pos.v1.ReversalReason
	(*SaleCommitted)(nil),       // 1: fnbpos.pos.v1.SaleCommitted
	(*SaleLine)(nil),            // 2: fnbpos.pos.v1.SaleLine
	(*Modifier)(nil),            // 3: fnbpos.pos.v1.Modifier
	(*KitchenTicket)(nil),       // 4: fnbpos.pos.v1.KitchenTicket
	(*KitchenLine)(nil),         // 5: fnbpos.pos.v1.KitchenLine
	(*KitchenTicketUpdate)(nil), // 6: fnbpos.pos.v1.KitchenTicketUpdate
	(*SaleReversed)(nil),        // 7: fnbpos.pos.v1.SaleReversed
	(*common.Envelope)(nil),     // 8: fnbpos.common.v1.Envelope
	(*common.Quantity)(nil),     // 9: fnbpos.common.v1.Quantity
	(*common.Money)(nil),        // 10: fnbpos.common.v1.Money
}
var file_pos_v1_sale_proto_depIdxs = []int32{
	8,  // 0: fnbpos.pos.v1.SaleCommitted.envelope:type_name -> fnbpos.common.v1.Envelope
	2,  // 1: fnbpos.pos.v1.SaleCommitted.lines:type_name -> fnbpos.pos.v1.SaleLine
	9,  // 2: fnbpos.pos.v1.SaleLine.qty:type_name -> fnbpos.common.v1.Quantity
	3,  // 3: fnbpos.pos.v1.SaleLine.modifiers:type_name -> fnbpos.pos.v1.Modifier
	10, // 4: fnbpos.pos.v1.SaleLine.unit_price:type_name -> fnbpos.common.v1.Money
	10, // 5: fnbpos.pos.v1.SaleLine.line_discount:type_name -> fnbpos.common.v1.Money
	10, // 6: fnbpos.pos.v1.SaleLine.tax:type_name -> fnbpos.common.v1.Money
	10, // 7: fnbpos.pos.v1.SaleLine.cogs_hint:type_name -> fnbpos.common.v1.Money
	9,  // 8: fnbpos.pos.v1.Modifier.qty:type_name -> fnbpos.common.v1.Quantity
	8,  // 9: fnbpos.pos.v1.KitchenTicket.envelope:type_name -> fnbpos.common.v1.Envelope
	5,  // 10: fnbpos.pos.v1.KitchenTicket.lines:type_name -> fnbpos.pos.v1.KitchenLine
	9,  // 11: fnbpos.pos.v1.KitchenLine.qty:type_name -> fnbpos.common.v1.Quantity
	8,  // 12: fnbpos.pos.v1.KitchenTicketUpdate.envelope:type_name -> fnbpos.common.v1.Envelope
	8,  // 13: fnbpos.pos.v1.SaleReversed.envelope:type_name -> fnbpos.common.v1.Envelope
	0,  // 14: fnbpos.pos.v1.SaleReversed.reason:type_name -> fnbpos.pos.v1.ReversalReason
	9,  // 15: fnbpos.pos.v1.SaleReversed.new_qty:type_name -> fnbpos.common.v1.Quantity
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_pos_v1_sale_proto_init() }
func file_pos_v1_sale_proto_init() {
	if File_pos_v1_sale_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pos_v1_sale_proto_rawDesc), len(file_pos_v1_sale_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pos_v1_sale_proto_goTypes,
		DependencyIndexes: file_pos_v1_sale_proto_depIdxs,
		EnumInfos:         file_pos_v1_sale_proto_enumTypes,
		MessageInfos:      file_pos_v1_sale_proto_msgTypes,
	}.Build()
	File_pos_v1_sale_proto = out.File
	file_pos_v1_sale_proto_goTypes = nil
	file_pos_v1_sale_proto_depIdxs = nil
}
