// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: fnb/v1/menu.proto

package fnb

import (
	common "github.com/rp-game/fnbpos-pb/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// fnb.menu.query.v1 (request/reply) — pos BOOTSTRAP/SYNC read-model (không dùng trên hot-path bán).
type MenuQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *common.Envelope       `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	OutletId      string                 `protobuf:"bytes,2,opt,name=outlet_id,json=outletId,proto3" json:"outlet_id,omitempty"`
	Locale        string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuQueryRequest) Reset() {
	*x = MenuQueryRequest{}
	mi := &file_fnb_v1_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuQueryRequest) ProtoMessage() {}

func (x *MenuQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fnb_v1_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuQueryRequest.ProtoReflect.Descriptor instead.
func (*MenuQueryRequest) Descriptor() ([]byte, []int) {
	return file_fnb_v1_menu_proto_rawDescGZIP(), []int{0}
}

func (x *MenuQueryRequest) GetEnvelope() *common.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *MenuQueryRequest) GetOutletId() string {
	if x != nil {
		return x.OutletId
	}
	return ""
}

func (x *MenuQueryRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type MenuQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *common.Envelope       `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // watermark: version cao nhất của snapshot (D3)
	Items         []*MenuItem            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuQueryResponse) Reset() {
	*x = MenuQueryResponse{}
	mi := &file_fnb_v1_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuQueryResponse) ProtoMessage() {}

func (x *MenuQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fnb_v1_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuQueryResponse.ProtoReflect.Descriptor instead.
func (*MenuQueryResponse) Descriptor() ([]byte, []int) {
	return file_fnb_v1_menu_proto_rawDescGZIP(), []int{1}
}

func (x *MenuQueryResponse) GetEnvelope() *common.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *MenuQueryResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MenuQueryResponse) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItemId    string                 `protobuf:"bytes,1,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         *common.Money          `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`       // giá net
	Channels      []string               `protobuf:"bytes,4,rep,name=channels,proto3" json:"channels,omitempty"` // allow-list: pos,kiosk,in_seat,pickup,online
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	Version       uint64                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`                                 // monotonic per (outlet, menu_item) — D3
	TaxGroup      string                 `protobuf:"bytes,7,opt,name=tax_group,json=taxGroup,proto3" json:"tax_group,omitempty"`                // nhóm thuế suất (DEC-05: đa suất per-line)
	OriginalPrice *common.Money          `protobuf:"bytes,8,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"` // giá gạch KM (nếu có)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_fnb_v1_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_fnb_v1_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_fnb_v1_menu_proto_rawDescGZIP(), []int{2}
}

func (x *MenuItem) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetPrice() *common.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *MenuItem) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *MenuItem) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *MenuItem) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MenuItem) GetTaxGroup() string {
	if x != nil {
		return x.TaxGroup
	}
	return ""
}

func (x *MenuItem) GetOriginalPrice() *common.Money {
	if x != nil {
		return x.OriginalPrice
	}
	return nil
}

// fnb.menu.changed — thêm/sửa/xoá (deleted=tombstone).
type MenuChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *common.Envelope       `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	OutletId      string                 `protobuf:"bytes,2,opt,name=outlet_id,json=outletId,proto3" json:"outlet_id,omitempty"`
	MenuItemId    string                 `protobuf:"bytes,3,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	Version       uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"` // tombstone: giữ tới hết cửa sổ replay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuChanged) Reset() {
	*x = MenuChanged{}
	mi := &file_fnb_v1_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuChanged) ProtoMessage() {}

func (x *MenuChanged) ProtoReflect() protoreflect.Message {
	mi := &file_fnb_v1_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuChanged.ProtoReflect.Descriptor instead.
func (*MenuChanged) Descriptor() ([]byte, []int) {
	return file_fnb_v1_menu_proto_rawDescGZIP(), []int{3}
}

func (x *MenuChanged) GetEnvelope() *common.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *MenuChanged) GetOutletId() string {
	if x != nil {
		return x.OutletId
	}
	return ""
}

func (x *MenuChanged) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *MenuChanged) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MenuChanged) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// fnb.price.changed — đổi giá/thuế-suất.
type PriceChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *common.Envelope       `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	OutletId      string                 `protobuf:"bytes,2,opt,name=outlet_id,json=outletId,proto3" json:"outlet_id,omitempty"`
	MenuItemId    string                 `protobuf:"bytes,3,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	Price         *common.Money          `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Version       uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceChanged) Reset() {
	*x = PriceChanged{}
	mi := &file_fnb_v1_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceChanged) ProtoMessage() {}

func (x *PriceChanged) ProtoReflect() protoreflect.Message {
	mi := &file_fnb_v1_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceChanged.ProtoReflect.Descriptor instead.
func (*PriceChanged) Descriptor() ([]byte, []int) {
	return file_fnb_v1_menu_proto_rawDescGZIP(), []int{4}
}

func (x *PriceChanged) GetEnvelope() *common.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *PriceChanged) GetOutletId() string {
	if x != nil {
		return x.OutletId
	}
	return ""
}

func (x *PriceChanged) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *PriceChanged) GetPrice() *common.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *PriceChanged) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// fnb.item.availability.changed — 86 / re-open.
type ItemAvailabilityChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *common.Envelope       `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	OutletId      string                 `protobuf:"bytes,2,opt,name=outlet_id,json=outletId,proto3" json:"outlet_id,omitempty"`
	MenuItemId    string                 `protobuf:"bytes,3,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	Available     bool                   `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	Version       uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemAvailabilityChanged) Reset() {
	*x = ItemAvailabilityChanged{}
	mi := &file_fnb_v1_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemAvailabilityChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemAvailabilityChanged) ProtoMessage() {}

func (x *ItemAvailabilityChanged) ProtoReflect() protoreflect.Message {
	mi := &file_fnb_v1_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemAvailabilityChanged.ProtoReflect.Descriptor instead.
func (*ItemAvailabilityChanged) Descriptor() ([]byte, []int) {
	return file_fnb_v1_menu_proto_rawDescGZIP(), []int{5}
}

func (x *ItemAvailabilityChanged) GetEnvelope() *common.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *ItemAvailabilityChanged) GetOutletId() string {
	if x != nil {
		return x.OutletId
	}
	return ""
}

func (x *ItemAvailabilityChanged) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *ItemAvailabilityChanged) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ItemAvailabilityChanged) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_fnb_v1_menu_proto protoreflect.FileDescriptor

const file_fnb_v1_menu_proto_rawDesc = "" +
	"\n" +
	"\x11fnb/v1/menu.proto\x12\rfnbpos.fnb.v1\x1a\x18common/v1/envelope.proto\"\x7f\n" +
	"\x10MenuQueryRequest\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.fnbpos.common.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\toutlet_id\x18\x02 \x01(\tR\boutletId\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\"\x94\x01\n" +
	"\x11MenuQueryResponse\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.fnbpos.common.v1.EnvelopeR\benvelope\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12-\n" +
	"\x05items\x18\x03 \x03(\v2\x17.fnbpos.fnb.v1.MenuItemR\x05items\"\x9a\x02\n" +
	"\bMenuItem\x12 \n" +
	"\fmenu_item_id\x18\x01 \x01(\tR\n" +
	"menuItemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x05price\x18\x03 \x01(\v2\x17.fnbpos.common.v1.MoneyR\x05price\x12\x1a\n" +
	"\bchannels\x18\x04 \x03(\tR\bchannels\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x04R\aversion\x12\x1b\n" +
	"\ttax_group\x18\a \x01(\tR\btaxGroup\x12>\n" +
	"\x0eoriginal_price\x18\b \x01(\v2\x17.fnbpos.common.v1.MoneyR\roriginalPrice\"\xb8\x01\n" +
	"\vMenuChanged\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.fnbpos.common.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\toutlet_id\x18\x02 \x01(\tR\boutletId\x12 \n" +
	"\fmenu_item_id\x18\x03 \x01(\tR\n" +
	"menuItemId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\"\xce\x01\n" +
	"\fPriceChanged\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.fnbpos.common.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\toutlet_id\x18\x02 \x01(\tR\boutletId\x12 \n" +
	"\fmenu_item_id\x18\x03 \x01(\tR\n" +
	"menuItemId\x12-\n" +
	"\x05price\x18\x04 \x01(\v2\x17.fnbpos.common.v1.MoneyR\x05price\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\"\xc8\x01\n" +
	"\x17ItemAvailabilityChanged\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.fnbpos.common.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\toutlet_id\x18\x02 \x01(\tR\boutletId\x12 \n" +
	"\fmenu_item_id\x18\x03 \x01(\tR\n" +
	"menuItemId\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\bR\tavailable\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversionB%Z#github.com/rp-game/fnbpos-pb/v1/fnbb\x06proto3"

var (
	file_fnb_v1_menu_proto_rawDescOnce sync.Once
	file_fnb_v1_menu_proto_rawDescData []byte
)

func file_fnb_v1_menu_proto_rawDescGZIP() []byte {
	file_fnb_v1_menu_proto_rawDescOnce.Do(func() {
		file_fnb_v1_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fnb_v1_menu_proto_rawDesc), len(file_fnb_v1_menu_proto_rawDesc)))
	})
	return file_fnb_v1_menu_proto_rawDescData
}

var file_fnb_v1_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fnb_v1_menu_proto_goTypes = []any{
	(*MenuQueryRequest)(nil),        // 0: fnbpos.fnb.v1.MenuQueryRequest
	(*MenuQueryResponse)(nil),       // 1: fnbpos.fnb.v1.MenuQueryResponse
	(*MenuItem)(nil),                // 2: fnbpos.fnb.v1.MenuItem
	(*MenuChanged)(nil),             // 3: fnbpos.fnb.v1.MenuChanged
	(*PriceChanged)(nil),            // 4: fnbpos.fnb.v1.PriceChanged
	(*ItemAvailabilityChanged)(nil), // 5: fnbpos.fnb.v1.ItemAvailabilityChanged
	(*common.Envelope)(nil),         // 6: fnbpos.common.v1.Envelope
	(*common.Money)(nil),            // 7: fnbpos.common.v1.Money
}
var file_fnb_v1_menu_proto_depIdxs = []int32{
	6, // 0: fnbpos.fnb.v1.MenuQueryRequest.envelope:type_name -> fnbpos.common.v1.Envelope
	6, // 1: fnbpos.fnb.v1.MenuQueryResponse.envelope:type_name -> fnbpos.common.v1.Envelope
	2, // 2: fnbpos.fnb.v1.MenuQueryResponse.items:type_name -> fnbpos.fnb.v1.MenuItem
	7, // 3: fnbpos.fnb.v1.MenuItem.price:type_name -> fnbpos.common.v1.Money
	7, // 4: fnbpos.fnb.v1.MenuItem.original_price:type_name -> fnbpos.common.v1.Money
	6, // 5: fnbpos.fnb.v1.MenuChanged.envelope:type_name -> fnbpos.common.v1.Envelope
	6, // 6: fnbpos.fnb.v1.PriceChanged.envelope:type_name -> fnbpos.common.v1.Envelope
	7, // 7: fnbpos.fnb.v1.PriceChanged.price:type_name -> fnbpos.common.v1.Money
	6, // 8: fnbpos.fnb.v1.ItemAvailabilityChanged.envelope:type_name -> fnbpos.common.v1.Envelope
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_fnb_v1_menu_proto_init() }
func file_fnb_v1_menu_proto_init() {
	if File_fnb_v1_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fnb_v1_menu_proto_rawDesc), len(file_fnb_v1_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fnb_v1_menu_proto_goTypes,
		DependencyIndexes: file_fnb_v1_menu_proto_depIdxs,
		MessageInfos:      file_fnb_v1_menu_proto_msgTypes,
	}.Build()
	File_fnb_v1_menu_proto = out.File
	file_fnb_v1_menu_proto_goTypes = nil
	file_fnb_v1_menu_proto_depIdxs = nil
}
