// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: fnb/v1/stock.proto

package fnb

import (
	common "github.com/rp-game/fnbpos-pb/v1/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// fnb.stock.shortfall — fnb -> pos: trừ kho fail / không đủ NVL sau khi đã bán.
// Đường báo ngược cho saga bán→trừ-kho (A6). Payload đầy đủ (lot/qty thiếu) bổ sung ở G0 (additive).
type StockShortfall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *common.Envelope       `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	OutletId      string                 `protobuf:"bytes,2,opt,name=outlet_id,json=outletId,proto3" json:"outlet_id,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,3,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SaleLineId    string                 `protobuf:"bytes,5,opt,name=sale_line_id,json=saleLineId,proto3" json:"sale_line_id,omitempty"`
	MenuItemId    string                 `protobuf:"bytes,6,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockShortfall) Reset() {
	*x = StockShortfall{}
	mi := &file_fnb_v1_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockShortfall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockShortfall) ProtoMessage() {}

func (x *StockShortfall) ProtoReflect() protoreflect.Message {
	mi := &file_fnb_v1_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockShortfall.ProtoReflect.Descriptor instead.
func (*StockShortfall) Descriptor() ([]byte, []int) {
	return file_fnb_v1_stock_proto_rawDescGZIP(), []int{0}
}

func (x *StockShortfall) GetEnvelope() *common.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *StockShortfall) GetOutletId() string {
	if x != nil {
		return x.OutletId
	}
	return ""
}

func (x *StockShortfall) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *StockShortfall) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *StockShortfall) GetSaleLineId() string {
	if x != nil {
		return x.SaleLineId
	}
	return ""
}

func (x *StockShortfall) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

var File_fnb_v1_stock_proto protoreflect.FileDescriptor

const file_fnb_v1_stock_proto_rawDesc = "" +
	"\n" +
	"\x12fnb/v1/stock.proto\x12\rfnbpos.fnb.v1\x1a\x18common/v1/envelope.proto\"\xe7\x01\n" +
	"\x0eStockShortfall\x126\n" +
	"\benvelope\x18\x01 \x01(\v2\x1a.fnbpos.common.v1.EnvelopeR\benvelope\x12\x1b\n" +
	"\toutlet_id\x18\x02 \x01(\tR\boutletId\x12!\n" +
	"\fwarehouse_id\x18\x03 \x01(\tR\vwarehouseId\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\x12 \n" +
	"\fsale_line_id\x18\x05 \x01(\tR\n" +
	"saleLineId\x12 \n" +
	"\fmenu_item_id\x18\x06 \x01(\tR\n" +
	"menuItemIdB%Z#github.com/rp-game/fnbpos-pb/v1/fnbb\x06proto3"

var (
	file_fnb_v1_stock_proto_rawDescOnce sync.Once
	file_fnb_v1_stock_proto_rawDescData []byte
)

func file_fnb_v1_stock_proto_rawDescGZIP() []byte {
	file_fnb_v1_stock_proto_rawDescOnce.Do(func() {
		file_fnb_v1_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fnb_v1_stock_proto_rawDesc), len(file_fnb_v1_stock_proto_rawDesc)))
	})
	return file_fnb_v1_stock_proto_rawDescData
}

var file_fnb_v1_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fnb_v1_stock_proto_goTypes = []any{
	(*StockShortfall)(nil),  // 0: fnbpos.fnb.v1.StockShortfall
	(*common.Envelope)(nil), // 1: fnbpos.common.v1.Envelope
}
var file_fnb_v1_stock_proto_depIdxs = []int32{
	1, // 0: fnbpos.fnb.v1.StockShortfall.envelope:type_name -> fnbpos.common.v1.Envelope
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fnb_v1_stock_proto_init() }
func file_fnb_v1_stock_proto_init() {
	if File_fnb_v1_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fnb_v1_stock_proto_rawDesc), len(file_fnb_v1_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fnb_v1_stock_proto_goTypes,
		DependencyIndexes: file_fnb_v1_stock_proto_depIdxs,
		MessageInfos:      file_fnb_v1_stock_proto_msgTypes,
	}.Build()
	File_fnb_v1_stock_proto = out.File
	file_fnb_v1_stock_proto_goTypes = nil
	file_fnb_v1_stock_proto_depIdxs = nil
}
