// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: common/v1/envelope.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is attached to every fnbpos message.
// Domain-neutral: only OPAQUE ids — no host types (no organizer/event/Item/room).
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // contract version, e.g. "1"
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`             // dedup/trace id
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                // opaque, host-assigned (internal trust)
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`          // business time (host clock / ClockPort)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_common_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_common_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Envelope) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// Money is minor-unit + ISO-4217 currency (multi-currency, host-neutral).
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountMinor   int64                  `protobuf:"varint,1,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"` // e.g. đồng (VND, scale 0) or cents (USD, scale 2)
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`                           // "VND", "USD", ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_common_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_common_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Money) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Quantity keeps decimal precision (as string) + an opaque unit-of-measure code,
// so "đếm cái" (pcs) vs "cân ký" (kg) vs "định lượng NVL" (ml) không bị mất UoM.
type Quantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // decimal-as-string, e.g. "1", "0.606", "330"
	Uom           string                 `protobuf:"bytes,2,opt,name=uom,proto3" json:"uom,omitempty"`     // opaque unit code: "pcs","kg","ml","shot",...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quantity) Reset() {
	*x = Quantity{}
	mi := &file_common_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quantity) ProtoMessage() {}

func (x *Quantity) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quantity.ProtoReflect.Descriptor instead.
func (*Quantity) Descriptor() ([]byte, []int) {
	return file_common_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *Quantity) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Quantity) GetUom() string {
	if x != nil {
		return x.Uom
	}
	return ""
}

var File_common_v1_envelope_proto protoreflect.FileDescriptor

const file_common_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x18common/v1/envelope.proto\x12\x10fnbpos.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\bEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"F\n" +
	"\x05Money\x12!\n" +
	"\famount_minor\x18\x01 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"2\n" +
	"\bQuantity\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x10\n" +
	"\x03uom\x18\x02 \x01(\tR\x03uomB(Z&github.com/rp-game/fnbpos-pb/v1/commonb\x06proto3"

var (
	file_common_v1_envelope_proto_rawDescOnce sync.Once
	file_common_v1_envelope_proto_rawDescData []byte
)

func file_common_v1_envelope_proto_rawDescGZIP() []byte {
	file_common_v1_envelope_proto_rawDescOnce.Do(func() {
		file_common_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_envelope_proto_rawDesc), len(file_common_v1_envelope_proto_rawDesc)))
	})
	return file_common_v1_envelope_proto_rawDescData
}

var file_common_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_v1_envelope_proto_goTypes = []any{
	(*Envelope)(nil),              // 0: fnbpos.common.v1.Envelope
	(*Money)(nil),                 // 1: fnbpos.common.v1.Money
	(*Quantity)(nil),              // 2: fnbpos.common.v1.Quantity
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_common_v1_envelope_proto_depIdxs = []int32{
	3, // 0: fnbpos.common.v1.Envelope.occurred_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_v1_envelope_proto_init() }
func file_common_v1_envelope_proto_init() {
	if File_common_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_envelope_proto_rawDesc), len(file_common_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_envelope_proto_goTypes,
		DependencyIndexes: file_common_v1_envelope_proto_depIdxs,
		MessageInfos:      file_common_v1_envelope_proto_msgTypes,
	}.Build()
	File_common_v1_envelope_proto = out.File
	file_common_v1_envelope_proto_goTypes = nil
	file_common_v1_envelope_proto_depIdxs = nil
}
